# Generated by Django 5.2.4 on 2025-08-10 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
