# Generated by Django 5.2.4 on 2025-08-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart_added_at_product_category_product_is_new'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterUser',
            new_name='Registerpage',
        ),
    ]
