# Generated by Django 5.2.4 on 2025-08-26 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{10,15}$', 'Mobile number must contain only numbers and be 10-15 digits long.')]),
        ),
    ]
